### PR TITLE
feat: enable autoscaling

### PR DESCRIPTION
**Pull request by sebastianlolv**
Enable autoscaling for app service.

### CODE REVIEW

**Comment by hknutsen** [comment]
Is it possible to create multiple autoscaling settings for a single app service plan? If yes, we should look into passing a map of autoscale settings instead to support creation of multiple settings.

**Comment by sebastianlolv** [comment]
Looks like its possible to create up to 20 profiles.

**Comment by hknutsen** [comment]
I see that there is now support for multiple profiles for a single autoscale setting, but is it possible to have multiple autoscale settings? 🤔

**Comment by sebastianlolv** [comment]
You can have up to 20 different profiles according to the terraform registry.

**Pull request closed without merging**
