### PR TITLE
feat: set diagnostic setting enabled log categories

### PR DESCRIPTION
**Pull request by kov117**
Test passed 👍🏽

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests fail immediately for me:

```console
│ Error: Missing required argument
│ 
│   on main.tf line 14, in module "app_service":
│   14: module "app_service" {
│ 
│ The argument "log_analytics_workspace_id" is required, but no definition
│ was found.
```

**Comment by hknutsen** [comment]
Also not sure if there are diagnostic categories available for app service plans.

**Comment by hknutsen** [comment]
If you check the ID of an App Service plan, you'll see that it follows the this format:

`/subscriptions/<subscription_id>/resourceGroups/<resource_group_name>/providers/Microsoft.Web/serverFarms/<app_service_plan_name>`.

Where:

- `/subscriptions/<subscription_id>` describes the subscription
- `/resourceGroups/<resource_group_name>` describes the resource group
- `/Microsoft.Web/serverFarms/<app_service_plan_name>` describes the App Service plan

I don't think there are any available log categories for `Microsoft.Web/serverFarms`.

**Comment by kov117** [comment]
Yes you are correct, after further attempts with testing and checking resource ID, i can see cleary now that app service does not support diagnostic categories. I will therefore close this branch.

**Pull request closed without merging**
